Repository TeamCommerce/backend-server, pull requests merged in 2023-08, with the labels that each got.

#3 chore: CI / Add Release Drafter, PR Template, Labeler, Reviwer Assign
  .github/PULL_REQUEST_TEMPLATE.md
  .github/release-drafter-config.yml
  .github/workflows/assign-workflow.yml
  .github/workflows/labeler.yml
  .github/workflows/release-drafter.yml
Labels: chore

#5 docs: README.md Update
  README.md
Labels: docs

#8 fix: repair to generage jacoco xml report (#7)
  .github/workflows/CI_gradle.yml
  README.md
  build.gradle
Labels: fix, chore

#10 chore: init Release Drafter
  .github/release-drafter-config.yml
  .github/workflows/CI_assign-reviewer.yml
  .github/workflows/CI_release-drafter.yml
Labels: patch

#11 fix: Release Drafter
  .github/release-drafter-config.yml
Labels: chore

#12 fix: Release Drafter
  .github/workflows/CI_release-drafter.yml
Labels: patch

#13 test: Release Drafter
  .github/workflows/CI_release-drafter.yml
Labels: patch

#14 feat: Add Test Codes For Test Release Drafter (#9)
  src/test/java/com/commerce/backendserver/api/member/MemberControllerTest.java
Labels: feat

#15 feat: Patch Release (#14)
  src/test/java/com/commerce/backendserver/api/member/MemberControllerTest.java
Labels: patch

#18 feat: Define exception handling structure (#17)
  build.gradle
  src/main/java/com/commerce/backendserver/global/exception/ApiExceptionHandler.java
  src/main/java/com/commerce/backendserver/global/exception/CommerceException.java
  src/main/java/com/commerce/backendserver/global/exception/error/ErrorCode.java
  src/main/java/com/commerce/backendserver/global/exception/error/ErrorResponse.java
  src/main/java/com/commerce/backendserver/global/exception/error/GlobalError.java
  src/test/java/com/commerce/backendserver/global/exception/ApiExceptionHandlerTest.java
Labels: feat

#21 feat: Inhance CI Logic
  .github/workflows/CI_assign-reviewer.yml
  .github/workflows/CI_gradle.yml
Labels: feat

#25 chore: Automated Deploy CD Pipeline
  .github/workflows/CICD_gradle.yml
  .github/workflows/CI_assignPullRequest.yml
  .github/workflows/CI_gradle.yml
  .github/workflows/CI_release-drafter.yml
  src/main/java/com/commerce/backendserver/api/presentation/member/MemberController.java
  src/main/java/com/commerce/backendserver/domain/member/Member.java
Labels: chore

#26 chore: Automated Deploy CD Pipeline
  .github/workflows/CICD_gradle.yml
  .github/workflows/CI_assignPullRequest.yml
  .github/workflows/CI_gradle.yml
  .github/workflows/CI_release-drafter.yml
  src/main/java/com/commerce/backendserver/api/presentation/member/MemberController.java
  src/main/java/com/commerce/backendserver/domain/member/Member.java
Labels: chore

#29 refactor: Refactor to Pet Entity Logic
  src/main/java/com/commerce/backendserver/global/auditing/BaseEntity.java
  src/main/java/com/commerce/backendserver/product/domain/Product.java
  src/main/java/com/commerce/backendserver/product/domain/ProductAttribute.java
  src/main/java/com/commerce/backendserver/product/domain/ProductInfo.java
  src/main/java/com/commerce/backendserver/product/domain/constants/ProductStatus.java
  src/main/java/com/commerce/backendserver/product/domain/promotion/Promotion.java
  src/main/java/com/commerce/backendserver/product/domain/promotion/PromotionPeriodAttribute.java
  src/main/java/com/commerce/backendserver/product/domain/promotion/PromotionPriceAttribute.java
  src/main/java/com/commerce/backendserver/product/domain/promotion/constants/PromotionStatus.java
  src/test/java/com/commerce/backendserver/member/presentation/MemberControllerTest.java
Labels: refactor

#38 chore: Add SpringBoot Banner.txt
  src/main/resources/banner.txt
Labels: chore

#33 refactor: Refactor Product Entity To Resolve Business Request
  src/main/java/com/commerce/backendserver/product/domain/Product.java
  src/main/java/com/commerce/backendserver/product/domain/ProductAttribute.java
  src/main/java/com/commerce/backendserver/product/domain/ProductCommonInfo.java
  src/main/java/com/commerce/backendserver/product/domain/ProductPriceAttribute.java
  src/main/java/com/commerce/backendserver/product/domain/constants/ProductBrand.java
  src/main/java/com/commerce/backendserver/product/domain/constants/ProductCategory.java
  src/main/java/com/commerce/backendserver/product/domain/option/ProductOption.java
  src/main/java/com/commerce/backendserver/product/domain/option/SelectionOption.java
  src/main/java/com/commerce/backendserver/product/domain/option/constants/ProductColor.java
  src/main/java/com/commerce/backendserver/product/domain/option/constants/ProductSize.java
  src/main/java/com/commerce/backendserver/product/domain/option/constants/ProductStatus.java
  src/main/java/com/commerce/backendserver/product/domain/promotion/Promotion.java
  src/test/java/com/commerce/backendserver/member/presentation/MemberControllerTest.java
Labels: refactor

#43 chore: Fixing the issue where the CI pipeline doesn't run for a specific PR
  .github/workflows/CICD_gradle.yml
Labels: chore

#40 feat: Add Constructor / Validation Method for Product Entity
  src/main/java/com/commerce/backendserver/global/exception/error/GlobalError.java
  src/main/java/com/commerce/backendserver/image/domain/Image.java
  src/main/java/com/commerce/backendserver/image/exception/ImageError.java
  src/main/java/com/commerce/backendserver/product/application/ProductFindService.java
  src/main/java/com/commerce/backendserver/product/application/ProductService.java
  src/main/java/com/commerce/backendserver/product/domain/Product.java
  src/main/java/com/commerce/backendserver/product/domain/ProductCommonInfo.java
  src/main/java/com/commerce/backendserver/product/domain/ProductImage.java
  src/main/java/com/commerce/backendserver/product/domain/ProductPriceAttribute.java
  src/main/java/com/commerce/backendserver/product/domain/constants/ProductBrand.java
  src/main/java/com/commerce/backendserver/product/domain/option/ProductOption.java
  src/main/java/com/commerce/backendserver/product/domain/option/SelectionOption.java
  src/main/java/com/commerce/backendserver/product/domain/promotion/Promotion.java
  src/main/java/com/commerce/backendserver/product/domain/promotion/PromotionPeriodAttribute.java
  src/main/java/com/commerce/backendserver/product/domain/promotion/PromotionPriceAttribute.java
  src/main/java/com/commerce/backendserver/product/dto/request/ProductCreateRequest.java
  src/main/java/com/commerce/backendserver/product/exception/ProductError.java
  src/main/java/com/commerce/backendserver/product/presentation/ProductSearchController.java
Labels: feat
