Repository TeamCommerce/backend-server, pull requests merged in 2023-09, with the labels that each got.

#51 feat: Init QueryDSL, Modify Jacoco Test Report
  .gitignore
  build.gradle
  src/main/java/com/commerce/backendserver/product/domain/ProductPriceAttribute.java
  src/main/java/com/commerce/backendserver/product/domain/option/ProductOption.java
  src/main/java/com/commerce/backendserver/product/domain/option/SelectionOption.java
  src/main/java/com/commerce/backendserver/product/domain/promotion/PromotionPriceAttribute.java
  src/test/java/com/commerce/backendserver/member/domain/MemberTest.java
Labels: feat

#54 feat: Define review entity
  src/main/java/com/commerce/backendserver/review/domain/Review.java
  src/main/java/com/commerce/backendserver/review/domain/additionalinfo/AdditionalInfo.java
  src/main/java/com/commerce/backendserver/review/domain/additionalinfo/AdditionalInfoList.java
  src/main/java/com/commerce/backendserver/review/domain/additionalinfo/constants/InfoName.java
  src/main/java/com/commerce/backendserver/review/domain/likereview/LikeReview.java
  src/main/java/com/commerce/backendserver/review/exception/ReviewError.java
Labels: feat

#56 feat: Merge Before Branching
  src/main/java/com/commerce/backendserver/auth/exception/AuthError.java
  src/main/java/com/commerce/backendserver/auth/infra/oauth/GoogleProfile.java
  src/main/java/com/commerce/backendserver/auth/infra/oauth/KakaoProfile.java
  src/main/java/com/commerce/backendserver/auth/infra/oauth/OAuthType.java
  src/main/java/com/commerce/backendserver/auth/infra/oauth/UserPrincipal.java
  src/main/java/com/commerce/backendserver/global/config/QueryDslConfig.java
  src/main/java/com/commerce/backendserver/image/domain/Image.java
  src/main/java/com/commerce/backendserver/image/domain/ProductImage.java
  src/main/java/com/commerce/backendserver/member/domain/Member.java
  src/main/java/com/commerce/backendserver/product/application/ProductFindService.java
  src/main/java/com/commerce/backendserver/product/application/ProductService.java
  src/main/java/com/commerce/backendserver/product/domain/Product.java
  src/main/java/com/commerce/backendserver/product/domain/ProductImage.java
  src/main/java/com/commerce/backendserver/product/dto/request/ProductCreateRequest.java
  src/test/java/com/commerce/backendserver/product/application/ProductFindServiceTest.java
Labels: feat

#59 feat: Refactor to DDD Packaging & Add Intergration Test
  src/main/java/com/commerce/backendserver/global/config/SecurityConfig.java
  src/main/java/com/commerce/backendserver/image/domain/ProductImage.java
  src/main/java/com/commerce/backendserver/product/application/ProductFindService.java
  src/main/java/com/commerce/backendserver/product/application/dto/ProductImageResponse.java
  src/main/java/com/commerce/backendserver/product/application/dto/ProductOptionResponse.java
  src/main/java/com/commerce/backendserver/product/application/dto/ProductSingleSimpleResponse.java
  src/main/java/com/commerce/backendserver/product/application/price/ProductPriceService.java
  src/main/java/com/commerce/backendserver/product/application/price/PromotionPriceUtil.java
  src/main/java/com/commerce/backendserver/product/application/price/promotion/FixDiscountCalculator.java
  src/main/java/com/commerce/backendserver/product/application/price/promotion/PromotionPriceUtil.java
  src/main/java/com/commerce/backendserver/product/application/price/promotion/RateDiscountCalculator.java
  src/main/java/com/commerce/backendserver/product/domain/Product.java
  src/main/java/com/commerce/backendserver/product/domain/ProductCommonInfo.java
  src/main/java/com/commerce/backendserver/product/domain/ProductPriceAttribute.java
  src/main/java/com/commerce/backendserver/product/domain/option/ProductOption.java
  src/main/java/com/commerce/backendserver/product/domain/option/ProductSelectionOption.java
  src/main/java/com/commerce/backendserver/product/domain/option/constants/ProductColor.java
  src/main/java/com/commerce/backendserver/product/domain/persistence/promotion/PromotionCommandRepository.java
  src/main/java/com/commerce/backendserver/product/domain/persistence/promotion/PromotionJpaRepository.java
  src/main/java/com/commerce/backendserver/product/domain/promotion/Promotion.java
  src/main/java/com/commerce/backendserver/product/domain/promotion/PromotionDiscountAttribute.java
  src/main/java/com/commerce/backendserver/product/domain/promotion/PromotionPeriodAttribute.java
  src/main/java/com/commerce/backendserver/product/domain/promotion/PromotionPriceAttribute.java
  src/main/java/com/commerce/backendserver/product/domain/promotion/constants/PromotionStatus.java
  src/main/java/com/commerce/backendserver/product/domain/promotion/constants/PromotionType.java
  src/main/java/com/commerce/backendserver/product/domain/promotion/discount/ApplyPromotionFactory.java
  src/main/java/com/commerce/backendserver/product/domain/promotion/discount/FixDiscountCalculator.java
  src/main/java/com/commerce/backendserver/product/domain/promotion/discount/PromotionPriceCalculator.java
  src/main/java/com/commerce/backendserver/product/domain/promotion/discount/RateDiscountCalculator.java
  src/main/java/com/commerce/backendserver/product/presentation/ProductSearchController.java
  src/test/java/com/commerce/backendserver/common/base/IntegrationTestBase.java
  src/test/java/com/commerce/backendserver/product/fixture/ProductFixture.java
  src/test/java/com/commerce/backendserver/product/fixture/ProductImageFixture.java
  src/test/java/com/commerce/backendserver/product/fixture/ProductOptionFixture.java
  src/test/java/com/commerce/backendserver/product/fixture/PromotionFixture.java
  src/test/java/com/commerce/backendserver/product/intergration/ProductFindApiTest.java
Labels: feat

#61 feat: Add Spring RestDocs API - Swagger3 UI Description Set
  src/test/java/com/commerce/backendserver/product/fixture/PromotionFixture.java
  src/test/java/com/commerce/backendserver/product/intergration/ProductFindApiTest.java
Labels: feat

#58 feat: Add Single Product Lookup API / Intergration Test
  src/main/java/com/commerce/backendserver/global/config/SecurityConfig.java
  src/main/java/com/commerce/backendserver/image/domain/ProductImage.java
  src/main/java/com/commerce/backendserver/product/application/ProductFindService.java
  src/main/java/com/commerce/backendserver/product/application/ProductService.java
  src/main/java/com/commerce/backendserver/product/application/dto/ProductImageResponse.java
  src/main/java/com/commerce/backendserver/product/application/dto/ProductOptionResponse.java
  src/main/java/com/commerce/backendserver/product/application/dto/ProductSingleSimpleResponse.java
  src/main/java/com/commerce/backendserver/product/domain/Product.java
  src/main/java/com/commerce/backendserver/product/domain/ProductCommandRepository.java
  src/main/java/com/commerce/backendserver/product/domain/ProductCommonInfo.java
  src/main/java/com/commerce/backendserver/product/domain/ProductPriceAttribute.java
  src/main/java/com/commerce/backendserver/product/domain/ProductQueryRepository.java
  src/main/java/com/commerce/backendserver/product/domain/infra/query/ProductQueryDslRepository.java
  src/main/java/com/commerce/backendserver/product/domain/infra/query/ProductQueryDslRepositoryImpl.java
  src/main/java/com/commerce/backendserver/product/domain/option/ProductOption.java
  src/main/java/com/commerce/backendserver/product/domain/option/ProductSelectionOption.java
  src/main/java/com/commerce/backendserver/product/domain/option/SelectionOption.java
  src/main/java/com/commerce/backendserver/product/domain/option/constants/ProductColor.java
  src/main/java/com/commerce/backendserver/product/domain/persistence/ProductCommandRepository.java
  src/main/java/com/commerce/backendserver/product/domain/persistence/ProductJpaRepository.java
  src/main/java/com/commerce/backendserver/product/domain/persistence/ProductQueryRepository.java
  src/main/java/com/commerce/backendserver/product/domain/persistence/promotion/PromotionCommandRepository.java
  src/main/java/com/commerce/backendserver/product/domain/persistence/promotion/PromotionJpaRepository.java
  src/main/java/com/commerce/backendserver/product/domain/promotion/Promotion.java
  src/main/java/com/commerce/backendserver/product/domain/promotion/PromotionDiscountAttribute.java
  src/main/java/com/commerce/backendserver/product/domain/promotion/PromotionPeriodAttribute.java
  src/main/java/com/commerce/backendserver/product/domain/promotion/PromotionPriceAttribute.java
  src/main/java/com/commerce/backendserver/product/domain/promotion/constants/PromotionStatus.java
  src/main/java/com/commerce/backendserver/product/domain/promotion/constants/PromotionType.java
  src/main/java/com/commerce/backendserver/product/domain/promotion/discount/ApplyPromotionFactory.java
  src/main/java/com/commerce/backendserver/product/domain/promotion/discount/FixDiscountCalculator.java
  src/main/java/com/commerce/backendserver/product/domain/promotion/discount/PromotionPriceCalculator.java
  src/main/java/com/commerce/backendserver/product/domain/promotion/discount/RateDiscountCalculator.java
  src/main/java/com/commerce/backendserver/product/exception/ProductError.java
  src/main/java/com/commerce/backendserver/product/presentation/ProductSearchController.java
  src/main/java/com/commerce/backendserver/review/application/ReviewService.java
  src/main/java/com/commerce/backendserver/review/exception/ReviewError.java
  src/test/java/com/commerce/backendserver/common/base/IntegrationTestBase.java
  src/test/java/com/commerce/backendserver/product/application/ProductFindServiceTest.java
  src/test/java/com/commerce/backendserver/product/fixture/ProductFixture.java
  src/test/java/com/commerce/backendserver/product/fixture/ProductImageFixture.java
  src/test/java/com/commerce/backendserver/product/fixture/ProductOptionFixture.java
  src/test/java/com/commerce/backendserver/product/fixture/PromotionFixture.java
  src/test/java/com/commerce/backendserver/product/intergration/ProductFindApiTest.java
Labels: feat

#60 feat: 리뷰 등록 API 테스팅
  build.gradle
  src/main/java/com/commerce/backendserver/global/config/SecurityConfig.java
  src/main/java/com/commerce/backendserver/global/exception/ApiExceptionHandler.java
  src/main/java/com/commerce/backendserver/review/application/utils/validator/AdditionalInfoValidator.java
  src/main/java/com/commerce/backendserver/review/domain/Review.java
  src/main/java/com/commerce/backendserver/review/domain/additionalinfo/AdditionalInfoList.java
  src/main/java/com/commerce/backendserver/review/domain/additionalinfo/constants/InfoName.java
  src/test/java/com/commerce/backendserver/common/authorize/CustomUserSecurityContextFactory.java
  src/test/java/com/commerce/backendserver/common/authorize/WithMockCustomUser.java
  src/test/java/com/commerce/backendserver/common/base/IntegrationTestBase.java
  src/test/java/com/commerce/backendserver/common/base/MockTestBase.java
  src/test/java/com/commerce/backendserver/common/fixture/CommonRequestFixture.java
  src/test/java/com/commerce/backendserver/common/fixture/ReviewFixture.java
  src/test/java/com/commerce/backendserver/common/utils/FileMockingUtils.java
  src/test/java/com/commerce/backendserver/common/utils/S3LinkUtils.java
  src/test/java/com/commerce/backendserver/image/application/ImageServiceTest.java
  src/test/java/com/commerce/backendserver/image/domain/ReviewImageTest.java
  src/test/java/com/commerce/backendserver/image/infra/BuketMetadataTest.java
  src/test/java/com/commerce/backendserver/image/infra/ImageManagerTest.java
  src/test/java/com/commerce/backendserver/review/application/ReviewServiceTest.java
  src/test/java/com/commerce/backendserver/review/application/utils/validator/AdditionalInfoValidatorTest.java
  src/test/java/com/commerce/backendserver/review/application/utils/validator/ContentsLengthValidatorTest.java
  src/test/java/com/commerce/backendserver/review/application/utils/validator/ScoreValidatorTest.java
  src/test/java/com/commerce/backendserver/review/domain/ReviewTest.java
  src/test/java/com/commerce/backendserver/review/domain/additionalinfo/AdditionalInfoListTest.java
  src/test/java/com/commerce/backendserver/review/domain/additionalinfo/AdditionalInfoTest.java
  src/test/java/com/commerce/backendserver/review/integration/ReviewAcceptanceFixture.java
  src/test/java/com/commerce/backendserver/review/integration/ReviewApiTest.java
  src/test/java/com/commerce/backendserver/review/presentation/ReviewControllerTest.java
  src/test/resources/images/hello1.jpg
  src/test/resources/images/hello2.jpg
  src/test/resources/images/hello3.png
  src/test/resources/sql/clean.sql
Labels: feat

#67 feat: Review, Image 관련 보충 테스팅
  lombok.config
  src/main/java/com/commerce/backendserver/global/exception/ApiExceptionHandler.java
  src/main/java/com/commerce/backendserver/global/exception/error/ErrorResponse.java
  src/main/java/com/commerce/backendserver/image/infra/ImageManager.java
  src/main/java/com/commerce/backendserver/review/domain/Review.java
  src/main/java/com/commerce/backendserver/review/domain/likereview/LikeReview.java
  src/test/java/com/commerce/backendserver/auth/application/filter/JwtFilterTest.java
  src/test/java/com/commerce/backendserver/common/controller/TestController.java
  src/test/java/com/commerce/backendserver/global/exception/ApiExceptionHandlerTest.java
  src/test/java/com/commerce/backendserver/global/exception/error/ErrorResponseTest.java
  src/test/java/com/commerce/backendserver/image/infra/BuketMetadataTest.java
  src/test/java/com/commerce/backendserver/image/infra/ImageManagerTest.java
  src/test/java/com/commerce/backendserver/review/domain/ReviewTest.java
  src/test/java/com/commerce/backendserver/review/domain/additionalinfo/AdditionalInfoListTest.java
  src/test/java/com/commerce/backendserver/review/domain/additionalinfo/AdditionalInfoTest.java
  src/test/java/com/commerce/backendserver/review/domain/likereview/LikeReviewTest.java
Labels: feat

#70 feat: 리뷰 통계정보 조회 API 응답스펙 구현
  src/main/java/com/commerce/backendserver/review/application/dto/response/AdditionalInfoStatistic.java
  src/main/java/com/commerce/backendserver/review/application/dto/response/RatioStatistic.java
  src/main/java/com/commerce/backendserver/review/application/dto/response/ReviewStatistics.java
  src/main/java/com/commerce/backendserver/review/domain/ReviewQueryRepository.java
Labels: feat

#78 feat: 리뷰 통계 정보를 위한 리뷰 조회쿼리를 구현한다
  src/main/java/com/commerce/backendserver/review/domain/ReviewQueryRepository.java
  src/main/java/com/commerce/backendserver/review/infra/query/ReviewQueryDslRepository.java
  src/main/java/com/commerce/backendserver/review/infra/query/ReviewQueryDslRepositoryImpl.java
  src/test/java/com/commerce/backendserver/common/base/RepositoryTestBase.java
  src/test/java/com/commerce/backendserver/common/config/QueryDslConfig.java
  src/test/java/com/commerce/backendserver/review/application/ReviewServiceTest.java
Labels: feat

#77 feat: Product Simple Response API
  src/main/java/com/commerce/backendserver/image/domain/ProductImage.java
  src/main/java/com/commerce/backendserver/image/domain/constants/ProductImageCategory.java
  src/main/java/com/commerce/backendserver/product/application/ProductFindService.java
  src/main/java/com/commerce/backendserver/product/application/dto/ProductImageResponse.java
  src/main/java/com/commerce/backendserver/product/application/dto/ProductOptionResponse.java
  src/main/java/com/commerce/backendserver/product/application/dto/ProductSingleDetailResponse.java
  src/main/java/com/commerce/backendserver/product/application/dto/ProductSingleSimpleResponse.java
  src/main/java/com/commerce/backendserver/product/domain/Product.java
  src/main/java/com/commerce/backendserver/product/domain/ProductPriceAttribute.java
  src/main/java/com/commerce/backendserver/product/domain/persistence/ProductQueryRepository.java
  src/main/java/com/commerce/backendserver/product/domain/promotion/discount/FixDiscountCalculator.java
  src/main/java/com/commerce/backendserver/product/domain/promotion/discount/PromotionPriceCalculator.java
  src/main/java/com/commerce/backendserver/product/domain/promotion/discount/RateDiscountCalculator.java
  src/main/java/com/commerce/backendserver/product/exception/ProductError.java
  src/main/java/com/commerce/backendserver/product/presentation/ProductSearchController.java
  src/test/java/com/commerce/backendserver/product/domain/ProductTest.java
  src/test/java/com/commerce/backendserver/product/fixture/ProductFixture.java
  src/test/java/com/commerce/backendserver/product/fixture/ProductImageFixture.java
  src/test/java/com/commerce/backendserver/product/intergration/ProductFindApiTest.java
Labels: feat

#76 fix: To Tracking Build Status in README.md
  README.md
Labels: fix

#81 refactor: 예외 응답스펙 및 에러코드 스펙 수정
  src/main/java/com/commerce/backendserver/auth/exception/AuthError.java
  src/main/java/com/commerce/backendserver/global/exception/ApiExceptionHandler.java
  src/main/java/com/commerce/backendserver/global/exception/error/ErrorCode.java
  src/main/java/com/commerce/backendserver/global/exception/error/ErrorResponse.java
  src/main/java/com/commerce/backendserver/global/exception/error/GlobalError.java
  src/main/java/com/commerce/backendserver/image/exception/ImageError.java
  src/main/java/com/commerce/backendserver/product/exception/ProductError.java
  src/main/java/com/commerce/backendserver/review/exception/ReviewError.java
  src/test/java/com/commerce/backendserver/auth/application/filter/JwtFilterTest.java
  src/test/java/com/commerce/backendserver/common/base/IntegrationTestBase.java
  src/test/java/com/commerce/backendserver/common/controller/TestController.java
  src/test/java/com/commerce/backendserver/global/exception/ApiExceptionHandlerTest.java
  src/test/java/com/commerce/backendserver/global/exception/error/ErrorResponseTest.java
Labels: refactor

#82 chore: Refactor Packaging / Init Testcode Convention
  src/main/java/com/commerce/backendserver/auth/application/CustomOAuth2LoginService.java
  src/main/java/com/commerce/backendserver/auth/application/filter/JwtAuthenticationFilter.java
  src/main/java/com/commerce/backendserver/global/config/SecurityConfig.java
  src/main/java/com/commerce/backendserver/member/infra/persistence/MemberQueryRepository.java
  src/main/java/com/commerce/backendserver/member/infra/persistence/MemberRepository.java
  src/main/java/com/commerce/backendserver/product/application/ProductFindService.java
  src/main/java/com/commerce/backendserver/product/domain/infra/query/ProductQueryDslRepository.java
  src/main/java/com/commerce/backendserver/product/infra/persistence/ProductCommandRepository.java
  src/main/java/com/commerce/backendserver/product/infra/persistence/ProductJpaRepository.java
  src/main/java/com/commerce/backendserver/product/infra/persistence/ProductQueryDslRepository.java
  src/main/java/com/commerce/backendserver/product/infra/persistence/ProductQueryDslRepositoryImpl.java
  src/main/java/com/commerce/backendserver/product/infra/persistence/ProductQueryRepository.java
  src/main/java/com/commerce/backendserver/product/infra/persistence/promotion/PromotionCommandRepository.java
  src/main/java/com/commerce/backendserver/product/infra/persistence/promotion/PromotionJpaRepository.java
  src/main/java/com/commerce/backendserver/review/application/ReviewService.java
  src/main/java/com/commerce/backendserver/review/infra/ReviewQueryRepository.java
  src/main/java/com/commerce/backendserver/review/infra/ReviewRepository.java
  src/main/java/com/commerce/backendserver/review/infra/persistence/ReviewQueryDslRepository.java
  src/main/java/com/commerce/backendserver/review/infra/persistence/ReviewQueryDslRepositoryImpl.java
  src/test/java/com/commerce/backendserver/auth/application/filter/JwtFilterTest.java
  src/test/java/com/commerce/backendserver/auth/domain/TokenQueryRepositoryTest.java
  src/test/java/com/commerce/backendserver/auth/domain/TokenTest.java
  src/test/java/com/commerce/backendserver/auth/infra/jwt/JwtProviderTest.java
  src/test/java/com/commerce/backendserver/auth/infra/oauth/GoogleUserProfileTest.java
  src/test/java/com/commerce/backendserver/auth/infra/oauth/KakaoUserProfileTest.java
  src/test/java/com/commerce/backendserver/auth/infra/oauth/OAuthProfileFactoryTest.java
  src/test/java/com/commerce/backendserver/auth/infra/oauth/OAuthTypeTest.java
  src/test/java/com/commerce/backendserver/auth/infra/oauth/UserPrincipalTest.java
  src/test/java/com/commerce/backendserver/common/base/IntegrationTestBase.java
  src/test/java/com/commerce/backendserver/global/exception/error/ErrorResponseTest.java
  src/test/java/com/commerce/backendserver/image/application/ImageServiceTest.java
  src/test/java/com/commerce/backendserver/image/domain/ReviewImageTest.java
  src/test/java/com/commerce/backendserver/image/infra/BuketMetadataTest.java
  src/test/java/com/commerce/backendserver/image/infra/ImageManagerTest.java
  src/test/java/com/commerce/backendserver/member/domain/MemberTest.java
  src/test/java/com/commerce/backendserver/member/infra/persistence/MemberQueryRepositoryTest.java
  src/test/java/com/commerce/backendserver/product/domain/ProductCommonInfoTest.java
  src/test/java/com/commerce/backendserver/product/domain/ProductPriceAttributeTest.java
  src/test/java/com/commerce/backendserver/product/domain/ProductTest.java
  src/test/java/com/commerce/backendserver/product/integration/ProductFindApiTest.java
  src/test/java/com/commerce/backendserver/review/application/ReviewServiceTest.java
  src/test/java/com/commerce/backendserver/review/application/utils/validator/AdditionalInfoValidatorTest.java
  src/test/java/com/commerce/backendserver/review/application/utils/validator/ContentsLengthValidatorTest.java
  src/test/java/com/commerce/backendserver/review/application/utils/validator/ScoreValidatorTest.java
  src/test/java/com/commerce/backendserver/review/domain/ReviewTest.java
  src/test/java/com/commerce/backendserver/review/domain/additionalinfo/AdditionalInfoListTest.java
  src/test/java/com/commerce/backendserver/review/domain/additionalinfo/AdditionalInfoTest.java
  src/test/java/com/commerce/backendserver/review/domain/likereview/LikeReviewTest.java
  src/test/java/com/commerce/backendserver/review/integration/ReviewAcceptanceFixture.java
  src/test/java/com/commerce/backendserver/review/integration/ReviewApiTest.java
  src/test/java/com/commerce/backendserver/review/presentation/ReviewControllerTest.java
  src/test/resources/sql/clean.sql
Labels: chore

#84 feat: 리뷰 엔티티 스펙에 productOptionId 추가
  src/main/java/com/commerce/backendserver/review/application/ReviewService.java
  src/main/java/com/commerce/backendserver/review/application/dto/request/CreateReviewRequest.java
  src/main/java/com/commerce/backendserver/review/domain/Review.java
  src/main/java/com/commerce/backendserver/review/infra/persistence/ReviewQueryRepository.java
  src/main/java/com/commerce/backendserver/review/infra/persistence/ReviewRepository.java
  src/main/java/com/commerce/backendserver/review/infra/persistence/query/ReviewQueryDslRepository.java
  src/main/java/com/commerce/backendserver/review/infra/persistence/query/ReviewQueryDslRepositoryImpl.java
  src/test/java/com/commerce/backendserver/common/fixture/ReviewFixture.java
  src/test/java/com/commerce/backendserver/image/domain/ReviewImageTest.java
  src/test/java/com/commerce/backendserver/review/application/ReviewServiceTest.java
  src/test/java/com/commerce/backendserver/review/domain/ReviewTest.java
  src/test/java/com/commerce/backendserver/review/domain/additionalinfo/AdditionalInfoListTest.java
  src/test/java/com/commerce/backendserver/review/domain/additionalinfo/AdditionalInfoTest.java
  src/test/java/com/commerce/backendserver/review/integration/ReviewAcceptanceFixture.java
  src/test/java/com/commerce/backendserver/review/integration/ReviewApiTest.java
Labels: feat

#88 feat: 리뷰 등록 서비스 로직에 ProductOptionId 검증 로직 추가
  src/main/java/com/commerce/backendserver/product/infra/persistence/ProductQueryRepository.java
  src/main/java/com/commerce/backendserver/review/application/ReviewService.java
  src/main/java/com/commerce/backendserver/review/exception/ReviewError.java
  src/test/java/com/commerce/backendserver/product/infra/persistence/ProductQueryRepositoryTest.java
  src/test/java/com/commerce/backendserver/review/application/ReviewServiceTest.java
Labels: feat

#91 feat&fix: 통계를 위한 리뷰 조회쿼리 테스팅 & 버그 픽스
  src/main/java/com/commerce/backendserver/review/infra/persistence/query/ReviewQueryDslRepositoryImpl.java
  src/test/java/com/commerce/backendserver/common/fixture/ReviewFixture.java
  src/test/java/com/commerce/backendserver/product/fixture/ProductFixture.java
  src/test/java/com/commerce/backendserver/product/fixture/ProductImageFixture.java
  src/test/java/com/commerce/backendserver/product/fixture/ProductOptionFixture.java
  src/test/java/com/commerce/backendserver/review/infra/persistence/ReviewQueryRepositoryTest.java
Labels: feat, fix
